name: venv_tremor_feedback
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=5.1
  - ipykernel=6.15.1
  - ipython=8.4.0
  - jupyter_client=7.3.4
  - jupyter_core=4.11.1
  - matplotlib=3.5.1
  - packaging=21.3
  - pandas=1.4.3
  - pip=22.1.2
  - python=3.10.4
  - scipy=1.7.3
  - setuptools=61.2.0
  - tqdm=4.64.0
  - pip:
    - numpy==1.22.4
    - pylint==2.14.5
    - pyxdf==1.16.3
    - scikit-learn==1.1.1
    - seaborn==0.12.0
    - tueplots==0.0.4

